version: "3.8"

services:
  kafka-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_KSQLDBSERVER: http://ksqldb0:8088

  kafka:
    image: docker.io/bitnami/kafka:3.8
    container_name: kafka
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - linkedin-network
    environment:
      #KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      - POSTGRES_DB=notificationDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Krishna@11
    networks:
      - linkedin-network
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=usersDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Krishna@11
    networks:
      - linkedin-network
    volumes:
      - user-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  post-db:
    image: postgres
    container_name: post-db
    environment:
      - POSTGRES_DB=postDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Krishna@11
    networks:
      - linkedin-network
    volumes:
      - post-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  connections-db:
    image: neo4j
    container_name: connections-db
    volumes:
      - connections-db-data:/data
    environment:
      - NEO4J_AUTH=neo4j/Krishna@11
    ports:
      - "7474:7474"
      - "7687:7687"

  discovery-server:
    image: ritik/linkedin-app/discovert-server
    container_name: discovery-server
    networks:
      - linkedin-network
    ports:
      - "8761:8761"

  notification-service:
    image: ritik/linkedin-app/notification-service
    container_name: notification-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - notification-db
      - kafka

  user-service:
    image: ritik/linkedin-app/user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - user-db

  post-service:
    image: ritik/linkedin-app/post-service
    container_name: post-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - kafka
      - post-db

  connections-service:
    image: ritik/linkedin-app/connections-service
    container_name: connections-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - kafka
      - connections-db

  api-gateway:
    image: ritik/linkedin-app/api-gateway
    container_name: api-gateway
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
    ports:
      - "7474:7474"

networks:
  linkedin-network:

volumes:
  kafka_data:
  notification-db-data:
  user-db-data:
  post-db-data:
  connections-db-data:
